name: ci-cd-apex

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: setup docker buildx
        uses: docker/setup-buildx-action@v3.4.0

      - name: Login to DockerHub
        uses: docker/login-action@v3.4.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/apex-trainer-hub:latest

  deploy:
    name: Deploy to vps amd
    needs: build
    runs-on: self-hosted

    steps:
      - name: run script to update image and restart container
        run: cd /home/ubuntu/scripts_CI_CD && chmod +x deploy_apex.sh && ./deploy_apex.sh