name: ci-cd-apex

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    name: Build and Deploy na VPS
    runs-on: self-hosted 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create Firebase Config File
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_JSON }}
        run: |
          echo "$FIREBASE_SECRET" > ./firebase-applet-config.json
      
      - name: Build Docker Image Locally
        run: |
          # Compila a imagem localmente na VPS sem enviar para lugar nenhum
          docker build -t apex-local:latest .

      - name: Run Deploy Script
        run: |
          chmod +x /home/ubuntu/scripts_CI_CD/deploy_apex.sh
          /home/ubuntu/scripts_CI_CD/deploy_apex.sh